# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_task_assignment_protos/cbba_consensus_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sbai_task_assignment_protos import update_iteration_pb2 as sbai__task__assignment__protos_dot_update__iteration__pb2
from sbai_task_assignment_protos import winning_agent_pb2 as sbai__task__assignment__protos_dot_winning__agent__pb2
from sbai_task_assignment_protos import winning_bid_pb2 as sbai__task__assignment__protos_dot_winning__bid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_task_assignment_protos/cbba_consensus_data.proto',
  package='sbai_task_assignment_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n5sbai_task_assignment_protos/cbba_consensus_data.proto\x12\x1bsbai_task_assignment_protos\x1a\x32sbai_task_assignment_protos/update_iteration.proto\x1a/sbai_task_assignment_protos/winning_agent.proto\x1a-sbai_task_assignment_protos/winning_bid.proto\"\x9f\x02\n\x11\x43\x42\x42\x41\x43onsensusData\x12\x42\n\x11winning_bids_list\x18\x01 \x03(\x0b\x32\'.sbai_task_assignment_protos.WinningBid\x12\x46\n\x13winning_agents_list\x18\x02 \x03(\x0b\x32).sbai_task_assignment_protos.WinningAgent\x12\x45\n\x0ftime_stamp_list\x18\x03 \x03(\x0b\x32,.sbai_task_assignment_protos.UpdateIteration\x12\x1a\n\x12\x62\x65lieves_converged\x18\x04 \x01(\x08\x12\x1b\n\x13\x62\x65havior_request_id\x18\x05 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[sbai__task__assignment__protos_dot_update__iteration__pb2.DESCRIPTOR,sbai__task__assignment__protos_dot_winning__agent__pb2.DESCRIPTOR,sbai__task__assignment__protos_dot_winning__bid__pb2.DESCRIPTOR,])




_CBBACONSENSUSDATA = _descriptor.Descriptor(
  name='CBBAConsensusData',
  full_name='sbai_task_assignment_protos.CBBAConsensusData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='winning_bids_list', full_name='sbai_task_assignment_protos.CBBAConsensusData.winning_bids_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='winning_agents_list', full_name='sbai_task_assignment_protos.CBBAConsensusData.winning_agents_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_stamp_list', full_name='sbai_task_assignment_protos.CBBAConsensusData.time_stamp_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='believes_converged', full_name='sbai_task_assignment_protos.CBBAConsensusData.believes_converged', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='behavior_request_id', full_name='sbai_task_assignment_protos.CBBAConsensusData.behavior_request_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=522,
)

_CBBACONSENSUSDATA.fields_by_name['winning_bids_list'].message_type = sbai__task__assignment__protos_dot_winning__bid__pb2._WINNINGBID
_CBBACONSENSUSDATA.fields_by_name['winning_agents_list'].message_type = sbai__task__assignment__protos_dot_winning__agent__pb2._WINNINGAGENT
_CBBACONSENSUSDATA.fields_by_name['time_stamp_list'].message_type = sbai__task__assignment__protos_dot_update__iteration__pb2._UPDATEITERATION
DESCRIPTOR.message_types_by_name['CBBAConsensusData'] = _CBBACONSENSUSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CBBAConsensusData = _reflection.GeneratedProtocolMessageType('CBBAConsensusData', (_message.Message,), {
  'DESCRIPTOR' : _CBBACONSENSUSDATA,
  '__module__' : 'sbai_task_assignment_protos.cbba_consensus_data_pb2'
  # @@protoc_insertion_point(class_scope:sbai_task_assignment_protos.CBBAConsensusData)
  })
_sym_db.RegisterMessage(CBBAConsensusData)


# @@protoc_insertion_point(module_scope)
