# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_task_assignment_protos/winning_bid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_task_assignment_protos/winning_bid.proto',
  package='sbai_task_assignment_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-sbai_task_assignment_protos/winning_bid.proto\x12\x1bsbai_task_assignment_protos\"0\n\nWinningBid\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x11\n\tbid_value\x18\x02 \x01(\x02\x62\x06proto3'
)




_WINNINGBID = _descriptor.Descriptor(
  name='WinningBid',
  full_name='sbai_task_assignment_protos.WinningBid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='sbai_task_assignment_protos.WinningBid.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bid_value', full_name='sbai_task_assignment_protos.WinningBid.bid_value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['WinningBid'] = _WINNINGBID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WinningBid = _reflection.GeneratedProtocolMessageType('WinningBid', (_message.Message,), {
  'DESCRIPTOR' : _WINNINGBID,
  '__module__' : 'sbai_task_assignment_protos.winning_bid_pb2'
  # @@protoc_insertion_point(class_scope:sbai_task_assignment_protos.WinningBid)
  })
_sym_db.RegisterMessage(WinningBid)


# @@protoc_insertion_point(module_scope)
