# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_behavior_protos/phase_execution_request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_behavior_protos/phase_execution_request.proto',
  package='sbai_behavior_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2sbai_behavior_protos/phase_execution_request.proto\x12\x14sbai_behavior_protos\":\n\x15PhaseExecutionRequest\x12!\n\x19should_execute_next_phase\x18\x01 \x01(\x08\x62\x06proto3'
)




_PHASEEXECUTIONREQUEST = _descriptor.Descriptor(
  name='PhaseExecutionRequest',
  full_name='sbai_behavior_protos.PhaseExecutionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='should_execute_next_phase', full_name='sbai_behavior_protos.PhaseExecutionRequest.should_execute_next_phase', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['PhaseExecutionRequest'] = _PHASEEXECUTIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhaseExecutionRequest = _reflection.GeneratedProtocolMessageType('PhaseExecutionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PHASEEXECUTIONREQUEST,
  '__module__' : 'sbai_behavior_protos.phase_execution_request_pb2'
  # @@protoc_insertion_point(class_scope:sbai_behavior_protos.PhaseExecutionRequest)
  })
_sym_db.RegisterMessage(PhaseExecutionRequest)


# @@protoc_insertion_point(module_scope)
