# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_task_assignment_protos/sbai_task_assignment_protos/update_iteration.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_task_assignment_protos/sbai_task_assignment_protos/update_iteration.proto',
  package='sbai_task_assignment_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nNsbai_task_assignment_protos/sbai_task_assignment_protos/update_iteration.proto\x12\x1bsbai_task_assignment_protos\"=\n\x0fUpdateIteration\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x18\n\x10update_iteration\x18\x02 \x01(\x05\x62\x06proto3'
)




_UPDATEITERATION = _descriptor.Descriptor(
  name='UpdateIteration',
  full_name='sbai_task_assignment_protos.UpdateIteration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='sbai_task_assignment_protos.UpdateIteration.robot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_iteration', full_name='sbai_task_assignment_protos.UpdateIteration.update_iteration', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['UpdateIteration'] = _UPDATEITERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateIteration = _reflection.GeneratedProtocolMessageType('UpdateIteration', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEITERATION,
  '__module__' : 'sbai_task_assignment_protos.sbai_task_assignment_protos.update_iteration_pb2'
  # @@protoc_insertion_point(class_scope:sbai_task_assignment_protos.UpdateIteration)
  })
_sym_db.RegisterMessage(UpdateIteration)


# @@protoc_insertion_point(module_scope)
