# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_sensor_protos/joy.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sbai_std_protos import header_pb2 as sbai__std__protos_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_sensor_protos/joy.proto',
  package='sbai_sensor_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1csbai_sensor_protos/joy.proto\x12\x12sbai_sensor_protos\x1a\x1csbai_std_protos/header.proto\"M\n\x03Joy\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.sbai_std_protos.Header\x12\x0c\n\x04\x61xes\x18\x02 \x03(\x02\x12\x0f\n\x07\x62uttons\x18\x03 \x03(\x05\x62\x06proto3'
  ,
  dependencies=[sbai__std__protos_dot_header__pb2.DESCRIPTOR,])




_JOY = _descriptor.Descriptor(
  name='Joy',
  full_name='sbai_sensor_protos.Joy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='sbai_sensor_protos.Joy.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='axes', full_name='sbai_sensor_protos.Joy.axes', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buttons', full_name='sbai_sensor_protos.Joy.buttons', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=159,
)

_JOY.fields_by_name['header'].message_type = sbai__std__protos_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['Joy'] = _JOY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Joy = _reflection.GeneratedProtocolMessageType('Joy', (_message.Message,), {
  'DESCRIPTOR' : _JOY,
  '__module__' : 'sbai_sensor_protos.joy_pb2'
  # @@protoc_insertion_point(class_scope:sbai_sensor_protos.Joy)
  })
_sym_db.RegisterMessage(Joy)


# @@protoc_insertion_point(module_scope)
