# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_tak_bridge_protos/mgrs_coordinate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_tak_bridge_protos/mgrs_coordinate.proto',
  package='sbai_tak_bridge_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,sbai_tak_bridge_protos/mgrs_coordinate.proto\x12\x16sbai_tak_bridge_protos\"g\n\x0eMgrsCoordinate\x12\x17\n\x0fzone_identifier\x18\x01 \x01(\t\x12\x19\n\x11square_identifier\x18\x02 \x01(\t\x12\x0f\n\x07\x65\x61sting\x18\x03 \x01(\x05\x12\x10\n\x08northing\x18\x04 \x01(\x05\x62\x06proto3'
)




_MGRSCOORDINATE = _descriptor.Descriptor(
  name='MgrsCoordinate',
  full_name='sbai_tak_bridge_protos.MgrsCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone_identifier', full_name='sbai_tak_bridge_protos.MgrsCoordinate.zone_identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='square_identifier', full_name='sbai_tak_bridge_protos.MgrsCoordinate.square_identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='easting', full_name='sbai_tak_bridge_protos.MgrsCoordinate.easting', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='northing', full_name='sbai_tak_bridge_protos.MgrsCoordinate.northing', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['MgrsCoordinate'] = _MGRSCOORDINATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MgrsCoordinate = _reflection.GeneratedProtocolMessageType('MgrsCoordinate', (_message.Message,), {
  'DESCRIPTOR' : _MGRSCOORDINATE,
  '__module__' : 'sbai_tak_bridge_protos.mgrs_coordinate_pb2'
  # @@protoc_insertion_point(class_scope:sbai_tak_bridge_protos.MgrsCoordinate)
  })
_sym_db.RegisterMessage(MgrsCoordinate)


# @@protoc_insertion_point(module_scope)
