# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_tak_bridge_protos/robot_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sbai_tak_bridge_protos import mgrs_pose_pb2 as sbai__tak__bridge__protos_dot_mgrs__pose__pb2
from sbai_tak_bridge_protos import fault_state_pb2 as sbai__tak__bridge__protos_dot_fault__state__pb2
from sbai_cortex_protos import cortex_state_update_pb2 as sbai__cortex__protos_dot_cortex__state__update__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_tak_bridge_protos/robot_state.proto',
  package='sbai_tak_bridge_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(sbai_tak_bridge_protos/robot_state.proto\x12\x16sbai_tak_bridge_protos\x1a&sbai_tak_bridge_protos/mgrs_pose.proto\x1a(sbai_tak_bridge_protos/fault_state.proto\x1a,sbai_cortex_protos/cortex_state_update.proto\"\xbc\x02\n\nRobotState\x12.\n\x04pose\x18\x01 \x01(\x0b\x32 .sbai_tak_bridge_protos.MgrsPose\x12\x11\n\tspeed_mph\x18\x02 \x01(\x01\x12\x17\n\x0f\x62\x61ttery_percent\x18\x03 \x01(\x01\x12\x1f\n\x17signal_strength_percent\x18\x04 \x01(\x01\x12\x37\n\x0b\x66\x61ult_state\x18\x05 \x01(\x0b\x32\".sbai_tak_bridge_protos.FaultState\x12\x37\n\x0e\x61utonomy_state\x18\x06 \x01(\x0e\x32\x1f.sbai_cortex_protos.CortexState\x12\x1f\n\x17\x66ront_camera_stream_key\x18\x07 \x01(\t\x12\x1e\n\x16\x62\x61\x63k_camera_stream_key\x18\x08 \x01(\tb\x06proto3'
  ,
  dependencies=[sbai__tak__bridge__protos_dot_mgrs__pose__pb2.DESCRIPTOR,sbai__tak__bridge__protos_dot_fault__state__pb2.DESCRIPTOR,sbai__cortex__protos_dot_cortex__state__update__pb2.DESCRIPTOR,])




_ROBOTSTATE = _descriptor.Descriptor(
  name='RobotState',
  full_name='sbai_tak_bridge_protos.RobotState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='sbai_tak_bridge_protos.RobotState.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_mph', full_name='sbai_tak_bridge_protos.RobotState.speed_mph', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_percent', full_name='sbai_tak_bridge_protos.RobotState.battery_percent', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signal_strength_percent', full_name='sbai_tak_bridge_protos.RobotState.signal_strength_percent', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fault_state', full_name='sbai_tak_bridge_protos.RobotState.fault_state', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='autonomy_state', full_name='sbai_tak_bridge_protos.RobotState.autonomy_state', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='front_camera_stream_key', full_name='sbai_tak_bridge_protos.RobotState.front_camera_stream_key', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='back_camera_stream_key', full_name='sbai_tak_bridge_protos.RobotState.back_camera_stream_key', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=513,
)

_ROBOTSTATE.fields_by_name['pose'].message_type = sbai__tak__bridge__protos_dot_mgrs__pose__pb2._MGRSPOSE
_ROBOTSTATE.fields_by_name['fault_state'].message_type = sbai__tak__bridge__protos_dot_fault__state__pb2._FAULTSTATE
_ROBOTSTATE.fields_by_name['autonomy_state'].enum_type = sbai__cortex__protos_dot_cortex__state__update__pb2._CORTEXSTATE
DESCRIPTOR.message_types_by_name['RobotState'] = _ROBOTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotState = _reflection.GeneratedProtocolMessageType('RobotState', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTSTATE,
  '__module__' : 'sbai_tak_bridge_protos.robot_state_pb2'
  # @@protoc_insertion_point(class_scope:sbai_tak_bridge_protos.RobotState)
  })
_sym_db.RegisterMessage(RobotState)


# @@protoc_insertion_point(module_scope)
