# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_geo_path_publisher_protos/geo_path_with_robot_id.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sbai_geographic_protos import geo_path_pb2 as sbai__geographic__protos_dot_geo__path__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_geo_path_publisher_protos/geo_path_with_robot_id.proto',
  package='sbai_geo_path_publisher_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n;sbai_geo_path_publisher_protos/geo_path_with_robot_id.proto\x12\x1esbai_geo_path_publisher_protos\x1a%sbai_geographic_protos/geo_path.proto\"Y\n\x12GeoPathWithRobotId\x12\x31\n\x08geo_path\x18\x01 \x01(\x0b\x32\x1f.sbai_geographic_protos.GeoPath\x12\x10\n\x08robot_id\x18\x02 \x01(\tb\x06proto3'
  ,
  dependencies=[sbai__geographic__protos_dot_geo__path__pb2.DESCRIPTOR,])




_GEOPATHWITHROBOTID = _descriptor.Descriptor(
  name='GeoPathWithRobotId',
  full_name='sbai_geo_path_publisher_protos.GeoPathWithRobotId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='geo_path', full_name='sbai_geo_path_publisher_protos.GeoPathWithRobotId.geo_path', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='sbai_geo_path_publisher_protos.GeoPathWithRobotId.robot_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=223,
)

_GEOPATHWITHROBOTID.fields_by_name['geo_path'].message_type = sbai__geographic__protos_dot_geo__path__pb2._GEOPATH
DESCRIPTOR.message_types_by_name['GeoPathWithRobotId'] = _GEOPATHWITHROBOTID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoPathWithRobotId = _reflection.GeneratedProtocolMessageType('GeoPathWithRobotId', (_message.Message,), {
  'DESCRIPTOR' : _GEOPATHWITHROBOTID,
  '__module__' : 'sbai_geo_path_publisher_protos.geo_path_with_robot_id_pb2'
  # @@protoc_insertion_point(class_scope:sbai_geo_path_publisher_protos.GeoPathWithRobotId)
  })
_sym_db.RegisterMessage(GeoPathWithRobotId)


# @@protoc_insertion_point(module_scope)
