# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_cortex_protos/cortex_state_update.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_cortex_protos/cortex_state_update.proto',
  package='sbai_cortex_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,sbai_cortex_protos/cortex_state_update.proto\x12\x12sbai_cortex_protos\"G\n\x11\x43ortexStateUpdate\x12\x32\n\tnew_state\x18\x01 \x01(\x0e\x32\x1f.sbai_cortex_protos.CortexState*^\n\x0b\x43ortexState\x12\x08\n\x04INIT\x10\x00\x12\r\n\tHIBERNATE\x10\x01\x12\x0b\n\x07STANDBY\x10\x02\x12\n\n\x06TELEOP\x10\x03\x12\r\n\tSOLO_AUTO\x10\x04\x12\x0e\n\nSWARM_AUTO\x10\x05\x62\x06proto3'
)

_CORTEXSTATE = _descriptor.EnumDescriptor(
  name='CortexState',
  full_name='sbai_cortex_protos.CortexState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIBERNATE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STANDBY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TELEOP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOLO_AUTO', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SWARM_AUTO', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=141,
  serialized_end=235,
)
_sym_db.RegisterEnumDescriptor(_CORTEXSTATE)

CortexState = enum_type_wrapper.EnumTypeWrapper(_CORTEXSTATE)
INIT = 0
HIBERNATE = 1
STANDBY = 2
TELEOP = 3
SOLO_AUTO = 4
SWARM_AUTO = 5



_CORTEXSTATEUPDATE = _descriptor.Descriptor(
  name='CortexStateUpdate',
  full_name='sbai_cortex_protos.CortexStateUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='new_state', full_name='sbai_cortex_protos.CortexStateUpdate.new_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=139,
)

_CORTEXSTATEUPDATE.fields_by_name['new_state'].enum_type = _CORTEXSTATE
DESCRIPTOR.message_types_by_name['CortexStateUpdate'] = _CORTEXSTATEUPDATE
DESCRIPTOR.enum_types_by_name['CortexState'] = _CORTEXSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CortexStateUpdate = _reflection.GeneratedProtocolMessageType('CortexStateUpdate', (_message.Message,), {
  'DESCRIPTOR' : _CORTEXSTATEUPDATE,
  '__module__' : 'sbai_cortex_protos.cortex_state_update_pb2'
  # @@protoc_insertion_point(class_scope:sbai_cortex_protos.CortexStateUpdate)
  })
_sym_db.RegisterMessage(CortexStateUpdate)


# @@protoc_insertion_point(module_scope)
