# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_swarm_protos/cbba_consensus_data_sbai.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sbai_std_protos import string_pb2 as sbai__std__protos_dot_string__pb2
from sbai_task_assignment_protos import cbba_consensus_data_pb2 as sbai__task__assignment__protos_dot_cbba__consensus__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_swarm_protos/cbba_consensus_data_sbai.proto',
  package='sbai_swarm_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0sbai_swarm_protos/cbba_consensus_data_sbai.proto\x12\x11sbai_swarm_protos\x1a\x1csbai_std_protos/string.proto\x1a\x35sbai_task_assignment_protos/cbba_consensus_data.proto\"\x80\x01\n\x15\x43\x42\x42\x41\x43onsensusDataSBAI\x12)\n\x08robot_id\x18\x01 \x01(\x0b\x32\x17.sbai_std_protos.String\x12<\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32..sbai_task_assignment_protos.CBBAConsensusDatab\x06proto3'
  ,
  dependencies=[sbai__std__protos_dot_string__pb2.DESCRIPTOR,sbai__task__assignment__protos_dot_cbba__consensus__data__pb2.DESCRIPTOR,])




_CBBACONSENSUSDATASBAI = _descriptor.Descriptor(
  name='CBBAConsensusDataSBAI',
  full_name='sbai_swarm_protos.CBBAConsensusDataSBAI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='sbai_swarm_protos.CBBAConsensusDataSBAI.robot_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='sbai_swarm_protos.CBBAConsensusDataSBAI.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=285,
)

_CBBACONSENSUSDATASBAI.fields_by_name['robot_id'].message_type = sbai__std__protos_dot_string__pb2._STRING
_CBBACONSENSUSDATASBAI.fields_by_name['data'].message_type = sbai__task__assignment__protos_dot_cbba__consensus__data__pb2._CBBACONSENSUSDATA
DESCRIPTOR.message_types_by_name['CBBAConsensusDataSBAI'] = _CBBACONSENSUSDATASBAI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CBBAConsensusDataSBAI = _reflection.GeneratedProtocolMessageType('CBBAConsensusDataSBAI', (_message.Message,), {
  'DESCRIPTOR' : _CBBACONSENSUSDATASBAI,
  '__module__' : 'sbai_swarm_protos.cbba_consensus_data_sbai_pb2'
  # @@protoc_insertion_point(class_scope:sbai_swarm_protos.CBBAConsensusDataSBAI)
  })
_sym_db.RegisterMessage(CBBAConsensusDataSBAI)


# @@protoc_insertion_point(module_scope)
