# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_system_alert_protos/system_alert.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_system_alert_protos/system_alert.proto',
  package='sbai_system_alert_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+sbai_system_alert_protos/system_alert.proto\x12\x18sbai_system_alert_protos\"Z\n\x0bSystemAlert\x12\x10\n\x08severity\x18\x01 \x01(\t\x12\x14\n\x0csubsystem_id\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\t\x12\x12\n\nalert_code\x18\x04 \x01(\tb\x06proto3'
)




_SYSTEMALERT = _descriptor.Descriptor(
  name='SystemAlert',
  full_name='sbai_system_alert_protos.SystemAlert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='severity', full_name='sbai_system_alert_protos.SystemAlert.severity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subsystem_id', full_name='sbai_system_alert_protos.SystemAlert.subsystem_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='sbai_system_alert_protos.SystemAlert.node_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alert_code', full_name='sbai_system_alert_protos.SystemAlert.alert_code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['SystemAlert'] = _SYSTEMALERT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemAlert = _reflection.GeneratedProtocolMessageType('SystemAlert', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMALERT,
  '__module__' : 'sbai_system_alert_protos.system_alert_pb2'
  # @@protoc_insertion_point(class_scope:sbai_system_alert_protos.SystemAlert)
  })
_sym_db.RegisterMessage(SystemAlert)


# @@protoc_insertion_point(module_scope)
