# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_geometry_protos/pose.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sbai_geometry_protos import point_pb2 as sbai__geometry__protos_dot_point__pb2
from sbai_geometry_protos import quaternion_pb2 as sbai__geometry__protos_dot_quaternion__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_geometry_protos/pose.proto',
  package='sbai_geometry_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fsbai_geometry_protos/pose.proto\x12\x14sbai_geometry_protos\x1a sbai_geometry_protos/point.proto\x1a%sbai_geometry_protos/quaternion.proto\"l\n\x04Pose\x12-\n\x08position\x18\x01 \x01(\x0b\x32\x1b.sbai_geometry_protos.Point\x12\x35\n\x0borientation\x18\x02 \x01(\x0b\x32 .sbai_geometry_protos.Quaternionb\x06proto3'
  ,
  dependencies=[sbai__geometry__protos_dot_point__pb2.DESCRIPTOR,sbai__geometry__protos_dot_quaternion__pb2.DESCRIPTOR,])




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='sbai_geometry_protos.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='sbai_geometry_protos.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='sbai_geometry_protos.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=238,
)

_POSE.fields_by_name['position'].message_type = sbai__geometry__protos_dot_point__pb2._POINT
_POSE.fields_by_name['orientation'].message_type = sbai__geometry__protos_dot_quaternion__pb2._QUATERNION
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'sbai_geometry_protos.pose_pb2'
  # @@protoc_insertion_point(class_scope:sbai_geometry_protos.Pose)
  })
_sym_db.RegisterMessage(Pose)


# @@protoc_insertion_point(module_scope)
