# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_geometry_protos/transform_stamped.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sbai_geometry_protos import transform_pb2 as sbai__geometry__protos_dot_transform__pb2
from sbai_std_protos import header_pb2 as sbai__std__protos_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_geometry_protos/transform_stamped.proto',
  package='sbai_geometry_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,sbai_geometry_protos/transform_stamped.proto\x12\x14sbai_geometry_protos\x1a$sbai_geometry_protos/transform.proto\x1a\x1csbai_std_protos/header.proto\"\x87\x01\n\x10TransformStamped\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.sbai_std_protos.Header\x12\x16\n\x0e\x63hild_frame_id\x18\x02 \x01(\t\x12\x32\n\ttransform\x18\x03 \x01(\x0b\x32\x1f.sbai_geometry_protos.Transformb\x06proto3'
  ,
  dependencies=[sbai__geometry__protos_dot_transform__pb2.DESCRIPTOR,sbai__std__protos_dot_header__pb2.DESCRIPTOR,])




_TRANSFORMSTAMPED = _descriptor.Descriptor(
  name='TransformStamped',
  full_name='sbai_geometry_protos.TransformStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='sbai_geometry_protos.TransformStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='child_frame_id', full_name='sbai_geometry_protos.TransformStamped.child_frame_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transform', full_name='sbai_geometry_protos.TransformStamped.transform', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=274,
)

_TRANSFORMSTAMPED.fields_by_name['header'].message_type = sbai__std__protos_dot_header__pb2._HEADER
_TRANSFORMSTAMPED.fields_by_name['transform'].message_type = sbai__geometry__protos_dot_transform__pb2._TRANSFORM
DESCRIPTOR.message_types_by_name['TransformStamped'] = _TRANSFORMSTAMPED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransformStamped = _reflection.GeneratedProtocolMessageType('TransformStamped', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMSTAMPED,
  '__module__' : 'sbai_geometry_protos.transform_stamped_pb2'
  # @@protoc_insertion_point(class_scope:sbai_geometry_protos.TransformStamped)
  })
_sym_db.RegisterMessage(TransformStamped)


# @@protoc_insertion_point(module_scope)
