# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_tak_bridge_protos/sbai_tak_bridge_protos/mgrs_pose.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_tak_bridge_protos/sbai_tak_bridge_protos/mgrs_pose.proto',
  package='sbai_tak_bridge_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=sbai_tak_bridge_protos/sbai_tak_bridge_protos/mgrs_pose.proto\x12\x16sbai_tak_bridge_protos\"z\n\tMgrsPoint\x12\x17\n\x0fzone_identifier\x18\x01 \x01(\t\x12\x19\n\x11square_identifier\x18\x02 \x01(\t\x12\x0f\n\x07\x65\x61sting\x18\x03 \x01(\x05\x12\x10\n\x08northing\x18\x04 \x01(\x05\x12\x16\n\x0e\x61ltitude_msl_m\x18\x05 \x01(\x01\"Y\n\x08MgrsPose\x12\x33\n\x08position\x18\x01 \x01(\x0b\x32!.sbai_tak_bridge_protos.MgrsPoint\x12\x18\n\x10true_heading_deg\x18\x02 \x01(\x01\x62\x06proto3'
)




_MGRSPOINT = _descriptor.Descriptor(
  name='MgrsPoint',
  full_name='sbai_tak_bridge_protos.MgrsPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone_identifier', full_name='sbai_tak_bridge_protos.MgrsPoint.zone_identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='square_identifier', full_name='sbai_tak_bridge_protos.MgrsPoint.square_identifier', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='easting', full_name='sbai_tak_bridge_protos.MgrsPoint.easting', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='northing', full_name='sbai_tak_bridge_protos.MgrsPoint.northing', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude_msl_m', full_name='sbai_tak_bridge_protos.MgrsPoint.altitude_msl_m', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=211,
)


_MGRSPOSE = _descriptor.Descriptor(
  name='MgrsPose',
  full_name='sbai_tak_bridge_protos.MgrsPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='sbai_tak_bridge_protos.MgrsPose.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='true_heading_deg', full_name='sbai_tak_bridge_protos.MgrsPose.true_heading_deg', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=302,
)

_MGRSPOSE.fields_by_name['position'].message_type = _MGRSPOINT
DESCRIPTOR.message_types_by_name['MgrsPoint'] = _MGRSPOINT
DESCRIPTOR.message_types_by_name['MgrsPose'] = _MGRSPOSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MgrsPoint = _reflection.GeneratedProtocolMessageType('MgrsPoint', (_message.Message,), {
  'DESCRIPTOR' : _MGRSPOINT,
  '__module__' : 'sbai_tak_bridge_protos.sbai_tak_bridge_protos.mgrs_pose_pb2'
  # @@protoc_insertion_point(class_scope:sbai_tak_bridge_protos.MgrsPoint)
  })
_sym_db.RegisterMessage(MgrsPoint)

MgrsPose = _reflection.GeneratedProtocolMessageType('MgrsPose', (_message.Message,), {
  'DESCRIPTOR' : _MGRSPOSE,
  '__module__' : 'sbai_tak_bridge_protos.sbai_tak_bridge_protos.mgrs_pose_pb2'
  # @@protoc_insertion_point(class_scope:sbai_tak_bridge_protos.MgrsPose)
  })
_sym_db.RegisterMessage(MgrsPose)


# @@protoc_insertion_point(module_scope)
