# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sbai_tak_bridge_protos/sbai_tak_bridge_protos/tak_joy.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sbai_tak_bridge_protos/sbai_tak_bridge_protos/tak_joy.proto',
  package='sbai_tak_bridge_protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n;sbai_tak_bridge_protos/sbai_tak_bridge_protos/tak_joy.proto\x12\x16sbai_tak_bridge_protos\"P\n\x06TakJoy\x12\x17\n\x0fthrottle_effort\x18\x01 \x01(\x01\x12\x14\n\x0csteer_effort\x18\x02 \x01(\x01\x12\x17\n\x0f\x62rake_momentary\x18\x03 \x01(\x08\x62\x06proto3'
)




_TAKJOY = _descriptor.Descriptor(
  name='TakJoy',
  full_name='sbai_tak_bridge_protos.TakJoy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='throttle_effort', full_name='sbai_tak_bridge_protos.TakJoy.throttle_effort', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='steer_effort', full_name='sbai_tak_bridge_protos.TakJoy.steer_effort', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brake_momentary', full_name='sbai_tak_bridge_protos.TakJoy.brake_momentary', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['TakJoy'] = _TAKJOY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TakJoy = _reflection.GeneratedProtocolMessageType('TakJoy', (_message.Message,), {
  'DESCRIPTOR' : _TAKJOY,
  '__module__' : 'sbai_tak_bridge_protos.sbai_tak_bridge_protos.tak_joy_pb2'
  # @@protoc_insertion_point(class_scope:sbai_tak_bridge_protos.TakJoy)
  })
_sym_db.RegisterMessage(TakJoy)


# @@protoc_insertion_point(module_scope)
